### PR TITLE
feat: support for stdin and piping

### LINKED ISSUE #235: Question: proper flow with resolve and lint
I'd like to know which flow do you guys use for resolve + lint.

My use case is I'd like to follow @philsturgeon suggestion in his blog and set an api-first workflow for our team, writing OpenAPI 3 with JSON Schema data models.

As part of this, I'd like to configure my CI to validate all schemas, and lint all OAS files.

Currently I have something like this:

```bash
# Verify JSON Schemas
$ ajv compile -s "schemas/*.json" -r "schemas/*.json" --verbose

# Convert JSON Schema models to OpenAPI-flavor and lint
$ speccy lint <(speccy resolve openapi.yaml -j)
```

The issue with this flow is that it seems speccy cannot work with stdin, so I either have to work with temporary files, or do [process substitution in bash](http://tldp.org/LDP/abs/html/process-sub.html) as above, but process substitution has known issues with error handling.

Am I missing anything? how do you guys do this?

What I'm thinking right now is providing a PR that enables stdin support for speccy, so that I can properly pipe the commands and have proper error handling, and maybe add some extra info in the readme:

```bash
$ speccy resolve openapi.yaml -j | speccy lint
```

### PR DESCRIPTION
**Pull request by dlouzan**
- validate properly flushes output so pipes stdout works
- lint accepts as input stdin (and pipe flows)
- move all verbose option messages to stderr so that pipes also work with verbose output

Fixes #235

### CODE REVIEW

**Comment by dlouzan** [comment]
Disclaimer: I haven't tested it in Windows, I don't really have a setup available for it :-)

**Comment by dlouzan** [comment]
This is of course also possible:

```sh
(feat/stdin-support= dd9713a)$ ./speccy.js lint <<EOF
> openapi: 3.0.0
> info:
>   contact:
>     name: Derp
>     email: derp@herp.com
>   version: 1.0.0
>   title: Swagger 2.0 Without Scheme
> paths: {}
> tags:
>   - name: Gym
>   - name: Pokemon
> EOF
Specification is valid, with 0 lint errors
```

**Comment by pderaaij** [comment]
Looks good to me, thanks for your contribution!

**Comment by MikeRalphson** [comment]
Successfully published:
 - oas-linter@3.0.1
 - oas-resolver@2.2.1
 - oas-validator@3.2.1

**Comment by dlouzan** [comment]
May I ping you guys on this? The PR is already a month old but seems the project is a bit stalled and building a stack of PR's. I'm currently working from a fork of this but integrating the functionality directly in the published package would be great :-)

Same goes for the fixes done by @MikeRalphson in https://github.com/Mermade/oas-kit/issues/152 and (potentially if you agree with it) #294.

Thanks!

**Comment by pderaaij** [comment]
I can't merge PRs unfortunately, we have to ping @djtarazona or @smythey21 for merging PRs.

**Comment by djtarazona** [comment]
Hey team, I will review this no later than this weekend. Sorry for the slowness on our side — we are working on getting better OSS processes in place and expect things to pick up soon.

**Comment by djtarazona** [comment]
@dlouzan LGTM, and works in my local smoke testing. Can you rebase and fix any conflicts? Then I'll get this merged in. Thanks!

**Comment by dlouzan** [comment]
I have just updated the branch, it was just some conflicts with the latest changes to package versions.

**Pull request merged**
