### PR TITLE
Fix #234, proper error handling

### LINKED ISSUE #234: v0.8.6 fails to show proper error on invalid schema
## Detailed description

The latest 0.8.6 version fails to print proper advice on invalid specs:

```
> speccy lint swagger.json

./node_modules/speccy/lint.js:83
        const { context, lintResults } = _options;
                ^

TypeError: Cannot destructure property `context` of 'undefined' or 'null'.
    at validator.validate (./node_modules/speccy/lint.js:83:42)
    at ./node_modules/call-me-maybe/index.js:13:28
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

whereas version 0.8.5 properly hints at the underlying issue:

```
> speccy lint swagger.json

Specification schema is invalid.

#/paths/~1api<hidden>/post/parameters/0
path parameters must appear in the path
```

## Context

I'm working on linting both v2 (using swagger2openapi) and v3 files from an older project. Some of the existing v2 files had not been linted before, and seems they are not even spec compliant.

The nodejs exception does not help finding out where the error actually lies, it looks to a user as if speccy is having an issue, instead of parsing an invalid spec.

## Your environment

* Node Version: Both latest v8 & v10 via nvm
* Operating system and version: Debian 9.6

### PR DESCRIPTION
**Pull request by pderaaij**

### CODE REVIEW

**Comment by pderaaij** [comment]
I have the same fix in #248.

Guess there are still some promise issues in `oas-validator` which we need to find, but it shouldn't break `speccy` like it does right now.

**Comment by philsturgeon** [comment]
@MikeRalphson I know there have been a lot of changes in oas-validator recently, should I merge this or wait for the updates?

**Comment by philsturgeon** [comment]
@pderaaij hey could you update the changelog for this? It should go under an `Unreleased` header instead of a specific version for now.

**Comment by pderaaij** [comment]
@philsturgeon this appears not to be the correct fix. I found the correct one for #248. 

I will update the PR in a few minutes.

**Comment by pderaaij** [comment]
@philsturgeon Updated the PR, this is a proper fix

**Comment by philsturgeon** [comment]
Thank you @pderaaij. I'm going to leave it to @MikeRalphson to review this one, if he approves I'll be happy to merge it.

**Comment by MikeRalphson** [comment]
@pderaaij should I test this one against the released `oas-validator@2.0.1` or against the upcoming release? If the latter, how are you linking the unreleased code to Speccy to test, referencing git urls in `package.json` or using `npm link` or some other approach?

**Comment by pderaaij** [comment]
@MikeRalphson I've tested it against `2.0.1` as well as the current state of `v5prep`. For the latter I take a poor mans approach of copying the last files in the branch to node_modules. 

The fix should work in both cases.

**Comment by MikeRalphson** [comment]
With the above change, `Speccy` gives the correct output and exit code on my `invalid`, `minimal` and `minimalLintable` examples, which I can post in a gist if useful.

**Comment by pderaaij** [comment]
Thanks for the review. I need to get used to all the new options in Javascript. Long time ago I developed in javascript/node.js ;-)

**Comment by MikeRalphson** [comment]
> Long time ago I developed in javascript/node.js ;-)

Doesn't show, I'd hate to try and write any Java or C# today!

**Comment by dkarlovi** [comment]
Is there a way for me to fetch a Docker image with this baked in so I can test it against #253?

**Comment by philsturgeon** [comment]
@dkarlovi sorry bud I was asleep! :) Merged now, so docker hub should be updated soon.

**Pull request merged**
