### PR TITLE
Added basic jekyll site

### LINKED ISSUE #54: "Would You Like To Know More?" Links
image

## Detailed description

Right now the errors are not always clear to folks who aren't super into OpenAPI specifications, so we need to provide links to more information.

## Context

Both @rachelsison and @iainmcgin have requested this feature this week. 😅

## Possible implementation

An easy step forward would be linking to the anchor that relates to the object being linted, so if we're saying "openapi" is missing the "tags" object, we can link to `https://swagger.io/specification/#oasObject`, which describes what the tags object should be and offers a link to learn more.  

I'd also like to get a mini site up on speccy.io, which will explain each of the built in suggestions in more detail. _Why_ do you need a tags object? Do I _really_ need to write descriptions for parameters?

### PR DESCRIPTION
**Pull request by philsturgeon**
Fixes #54

Added links to a new site which explains rules a bit better:

screen shot 2018-06-13 at 2 41 30 pm

The site is super basic, some have examples, etc. This will be improved over time. 

screen shot 2018-06-13 at 2 34 19 pm

### CODE REVIEW

**Comment by philsturgeon** [comment]
@rachelsison @iainmcgin @mryave and anyone else who was interested in #54, please could you take  a look at this PR?

**Comment by dangoosby** [comment]
@philsturgeon shouldn't you edit the `./.circleci/config.yml` so jekyll can build and test? Also, add a Dockerfile (depending on deployment/hosting)?

Otherwise this is a great start to Speccy.io!! 🚀 👍

**Comment by philsturgeon** [comment]
Great point on circle but I’ll address that in a follow up. 

This is gonna be github pages so that’s nice and easy!

**Comment by MikeRalphson** [comment]
Is there a link to a gh-pages preview of the site? Sorry if being dim.

**Comment by philsturgeon** [comment]
I’m gonna use the /docs folder, it’s a new alternative to gh-pages that’s a bit less confusing to use, and let’s them both update in the same PR :)

—
Phil Sturgeon

**Pull request merged**
